# Interactive component
<script src="https://d3js.org/d3.v6.js"></script>
 <head> 
    <title>Id Attributes</title> 
    <style>  
         #KD { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         }         
         #GDR { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         }
         #DPM { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
         #CSM { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         } 
         #RANK { 
            color:black; 
            font-size:14px; 
            font-weight:bold; 
            text-align:center; 
         }
         
	

    </style> 
</head> 
 <div id="plot"></div> 
 <p style="font-size: 24px"  class="fancy"> Choose your interested team stats </p>
 <p id="KD" ><button type="button">KD</button></p>
 <p id="GDR"><button type="button">GDR</button></p>
 <p id="DPM"><button type="button">DPM</button></p>
 <p id="CSM"><button type="button">CSM</button></p>
 <p id="RANK"><button type="button">RANK</button></p>

 



 

 
 
 <script>
 var w = 700;
  var h = 400;
  var margin = {top: 80, right: 0, bottom: 25,
      left: 50};
  var innerWidth = w - margin.left - margin.right;
  var innerHeight = h - margin.top - margin.bottom;

  var bardata = [0.45, 0.56, 0.57, 0.83, 0.82, 0.91, 0.92, 0.84, 1.19, 0.94, 1.21, 1.16, 1.15, 1.1, 1.62, 1.53];
  

  var xScale = d3.scaleBand()
      .domain(d3.range(bardata.length))
      .range([0, innerWidth])
      .paddingInner(0.1);

  var yScale = d3.scaleLinear()
      .domain([0, d3.max(bardata)])
      .range([innerHeight,0]);

  var xAxis = d3.axisBottom()
      .scale(xScale)
      .tickFormat((d, i) => ["DFM","FNC","FPX","C9","MAD","RGE","HLE","LNG","TL","100T","PSG","RNG","EDG","GENG","T1","DK" ][i]);

  var yAxis = d3.axisLeft()
      		.scale(yScale);

// add svg

  var svg = d3.select("div#plot")
    .append("svg")
      .attr("width", w)
      .attr("height", h);

// add background rectangle

  svg.append("rect")
      .attr("x", 0)
      .attr("y", 0)
      .attr("width", w)
      .attr("height", h)
      .attr("fill", "white");

// add bars as a group

  var bars = svg.append("g")
      .attr("id", "plot")
      .attr("transform", `translate (${margin.left}, ${margin.top})`)
    .selectAll("rect")
      .data(bardata);

  bars.enter().append("rect")
      .attr("x", (d, i) => xScale(i))
      .attr("y", d => yScale(d))
      .attr("width", xScale.bandwidth())
      .attr("height", d => innerHeight - yScale(d))
      .attr("fill", "lightblue");

// add axes

  svg.append("g")
      .attr("class", "xAxis")
      .attr("transform", `translate (${margin.left}, ${h - margin.bottom})`)
      .call(xAxis);

  svg.append("g")
      .attr("class", "yAxis")
      .attr("transform", `translate (${margin.left}, ${margin.top})`)
      .call(yAxis);

  svg.append("text")
     .attr("transform", "translate(100,0)")
     .attr("x", 15)
     .attr("y", 40)
     .attr("font-size", "24px")
     .text("2021 World Championships");
   


// General Update Pattern
  function update(data) {
      xScale.domain(d3.range(data.length));

      yScale.domain([0, d3.max(data)]);

      var bars = svg.select("g")
          .selectAll("rect")
          .data(data);

      bars.enter()
        .append("rect")
          .attr("x", w)
          .attr("y", d => yScale(d))
          .attr("width", xScale.bandwidth())
          .attr("height", d => innerHeight - yScale(d))
          .attr("fill", "blue")
        .merge(bars)
          .transition()
          .duration(2000)
          .ease(d3.easeLinear)
          .attr("x", (d, i) => xScale(i))
          .attr("y", d => yScale(d))
          .attr("width", xScale.bandwidth())
          .attr("height", d => innerHeight - yScale(d));
	

      bars.exit().remove();

      svg.select(".xAxis")
          .transition()
          .duration(2000)
          .ease(d3.easeLinear)
          .call(xAxis);

      svg.select(".yAxis")
          .transition()
          .duration(2000)
          .ease(d3.easeLinear)
          .call(yAxis);
    }
    
    
    
  // Interactivity
  
    d3.selectAll("p")
        .on("click", function() {

            var paraID = d3.select(this).attr("id");

            if (paraID == "KD") {
              bardata = [0.45, 0.56, 0.57, 0.83, 0.82, 0.91, 0.92, 0.84, 1.19, 0.94, 1.21, 1.16, 1.15, 1.1, 1.62, 1.53];}
            else if (paraID == "GDR") {
              bardata = [31.03,31.22,31.67,32.73,33.42,33.43,34.28,34.67,34.68,35.05,35.67,36.07,36.78,37,37.07,37.68 ];}
            else if (paraID == "DPM") {
              bardata = [1427, 2164, 1361, 1572, 1856, 1702, 1838, 1648, 1693, 1554, 1914, 1908, 1848, 1756, 1751, 1902];}
            else if (paraID == "CSM") {
		          bardata = [30.1,30.5,31,31,31.9,31.9,32,32.1,32.1,32.3,32.7,33.1,33.2,33.3,33.4,33.6 ];}
		        else {bardata = [16,16,16,8,8,16,8,16,16,16,16,8,1,4,4,2];}

            update(bardata);

        });
 
 </script>
 
<p> 
The interactive bar graph shows the different team stats in 2022 lol World Championship by teams. We select 5 variables:
KD:Kill/Death, GDRL:Game Duration, DPM: damage to champions per minute, CSM:creeps per minute and Rank. Click on the buttons to see the stats varies.
</p>
<p> 

</p>
