# Conclusion

英雄联盟s11全球总决赛已经完满结束。作为当下最火热的电竞赛事，这点燃了全球无数玩家的关注。s11的决赛观赛人数甚至有超七千万人同时在线观看。除了赛事以外，lol在日常里也是十分受到玩家的喜欢。根据官方的统计，lol每天在线玩家数量也超过800万人。可见其的火热程度。The League of Legends s11 world champions have ended successfully. As the hottest e-sports event now, it has attracted the attention of countless players around the world. There were even more than 70 million people watching the s11 finals online at the same time. In addition to champions, The League of Legends is also popular among players in daily life. According to official statistics from Riot company, there are more than 8 million online players on LOL every day. It can be seen how attracitve it is.
而对于每场比赛，大家最关注的莫过于最后的胜负了。通常大家总是通过个人发挥和操作来预估比赛的输赢。但lol游戏已经其实形成了一个庞大的数据库。所以我们在这次的project里尝试用数据来解释为什么一个队伍更容易赢得胜利。我们根据游戏机制，设定了三个方面来研究队伍数据看赢得多的队伍有哪些特质。并且我们也对不同位置的选手进行了评估来研究不同位置的选手需要更侧重自己的那些方面来提高胜率。For each game, everyone is most concerned about the final results: victory or defeat. Usually individuals always predicts the win or loss of the game through player’s operation. However, The League of Legends has actually formed a huge database. So we tried to use data in this project to explain why a team is easier to win than others. According to the game mechanism, we set up three aspects to study the team data to see what characteristics the winning team has. And we also evaluated players in different positions to study what players in different positions need to do to improve their winning percentage.
事实上每场比赛，选手的状态，团队的状态都会对最后的结果有所影响。由于人的不稳定性，通过数据来判定一场比赛是否一定能赢或许结果会有所偏差。但是通过数据，我们也能发现一些规律和制胜的特质。这也是为什么lol战队往往会配备好的数据分析师。In fact, the state of the players and the team will have an impact on the final result of each game. Due to human instability, the result predicted by data might be incorrect sometimes. But through data, we can indeed discover some rules and winning traits. This is why the lol team are always equipped with good data analysts.
由于时间限制，我们只分析了本次世界赛的数据。总的游戏场数比较少，并且没有考虑到bp，英雄搭配和克制的关系. Due to time constraints, we only analyzed the data of this world champions. The total number of games is relatively small, and the ban/pick, hero matching and restraint is not considered this time.It might be a good direction to corporate more variables into analysis?
除此以外，职业选手打比赛和普通人打比赛也会有所差距。我们得到的结论其实是适用于职业比赛。如果想要了解在rank里面如何能赢，我们还需要另外分析rank的数据.In addition, there will be a gap between professional players and normal players. The conclusion we got is actually applicable to professional competitions. If we want to understand how to win in rank, we also need to analyze rank data separately.